 export const Statename = [
   { label:"Alaska"},
   { label:"Alabama"},
   { label:"Arkansas"},
  { label: "American Samoa"},
  { label: "Arizona"},
   { label:"California"},
 { label:  "Colorado"},
 { label:  "Connecticut"},
 { label:  "District of Columbia"},
 { label:  "Delaware"},
 { label:  "Florida"},
 { label:  "Georgia"},
 { label:  "Guam"},
 { label:  "Hawaii"},
 { label:  "Iowa"},
 { label:  "Idaho"},
 { label:  "Illinois"},
 { label:  "Indiana"},
 { label:  "Kansas"},
 { label:  "Kentucky"},
 { label:  "Louisiana"},
 { label:  "Massachusetts"},
 { label:  "Maryland"},
 { label:  "Maine"},
 { label:  "Michigan"},
 { label:  "Minnesota"},
 { label:  "Missouri"},
 { label:  "Mississippi"},
 { label:  "Montana"},
 { label:  "North Carolina"},
 { label:  "North Dakota"},
 { label:  "Nebraska"},
 { label:  "New Hampshire"},
 { label:  "New Jersey"},
 { label:  "New Mexico"},
 { label:  "Nevada"},
 { label:  "New York"},
 { label:  "Ohio"},
 { label:  "Oklahoma"},
 { label:  "Oregon"},
 { label:  "Pennsylvania"},
 { label:  "Puerto Rico"},
 { label:  "Rhode Island"},
 { label:  "South Carolina"},
 { label:  "South Dakota"},
 { label:  "Tennessee"},
 { label:  "Texas"},
 { label:  "Utah"},
  { label: "Virginia"},
  { label: "Virgin Islands"},
  { label: "Vermont"},
  { label: "Washington"},
  { label: "Wisconsin"},
  { label: "West Virginia"},
  { label: "Wyoming"},
];