import { Rent } from "@components/Common"
import Hero from "@components/Common/Home/Hero"
import React from "react"

const RentRoomPage = ({ loads }) => {
  return (
    <>
      <Hero
        reverse
        primaryText={"Buy or Sell, Anything"}
        secondaryText={"Find Jobs, Loads, truck and more."}
      />
      <Rent isRooms={true} loadsData={loads} />
    </>
  )
}

RentRoomPage.defaultProps = {
  loads: [
    {
      name: "Rooms For Rent",
      date: "25-04-2022, 11:30 PM",
      price: 50000,
      state: "MASSACHUSETTS",
      city: "BOSTON",
      type: "Share Room",
      rooms: 3,
      img: "/images/home.jpg",
    },
    {
      name: "Rooms For Rent",
      date: "25-04-2022, 11:30 PM",
      price: 50000,
      state: "MASSACHUSETTS",
      city: "BOSTON",
      type: "Share Room",
      rooms: 3,
      img: "/images/home.jpg",
    },
    {
      name: "Rooms For Rent",
      date: "25-04-2022, 11:30 PM",
      price: 50000,
      state: "MASSACHUSETTS",
      city: "BOSTON",
      type: "Share Room",
      rooms: 3,
      img: "/images/home.jpg",
    },
    {
      name: "Rooms For Rent",
      date: "25-04-2022, 11:30 PM",
      price: 50000,
      state: "MASSACHUSETTS",
      city: "BOSTON",
      type: "Share Room",
      rooms: 3,
      img: "/images/home.jpg",
    },
    {
      name: "Rooms For Rent",
      date: "25-04-2022, 11:30 PM",
      price: 50000,
      state: "MASSACHUSETTS",
      city: "BOSTON",
      type: "Share Room",
      rooms: 3,
      img: "/images/home.jpg",
    },
    {
      name: "Rooms For Rent",
      date: "25-04-2022, 11:30 PM",
      price: 50000,
      state: "MASSACHUSETTS",
      city: "BOSTON",
      type: "Share Room",
      rooms: 3,
      img: "/images/home.jpg",
    },
    {
      name: "Rooms For Rent",
      date: "25-04-2022, 11:30 PM",
      price: 50000,
      state: "MASSACHUSETTS",
      city: "BOSTON",
      type: "Share Room",
      rooms: 3,
      img: "/images/home.jpg",
    },
    {
      name: "Rooms For Rent",
      date: "25-04-2022, 11:30 PM",
      price: 50000,
      state: "MASSACHUSETTS",
      city: "BOSTON",
      type: "Share Room",
      rooms: 3,
      img: "/images/home.jpg",
    },
    {
      name: "Rooms For Rent",
      date: "25-04-2022, 11:30 PM",
      price: 50000,
      state: "MASSACHUSETTS",
      city: "BOSTON",
      type: "Share Room",
      rooms: 3,
      img: "/images/home.jpg",
    },
    {
      name: "Rooms For Rent",
      date: "25-04-2022, 11:30 PM",
      price: 50000,
      state: "MASSACHUSETTS",
      city: "BOSTON",
      type: "Share Room",
      rooms: 3,
      img: "/images/home.jpg",
    },
    {
      name: "Rooms For Rent",
      date: "25-04-2022, 11:30 PM",
      price: 50000,
      state: "MASSACHUSETTS",
      city: "BOSTON",
      type: "Share Room",
      rooms: 3,
      img: "/images/home.jpg",
    },
    {
      name: "Rooms For Rent",
      date: "25-04-2022, 11:30 PM",
      price: 50000,
      state: "MASSACHUSETTS",
      city: "BOSTON",
      type: "Share Room",
      rooms: 3,
      img: "/images/home.jpg",
    },
    {
      name: "Rooms For Rent",
      date: "25-04-2022, 11:30 PM",
      price: 50000,
      state: "MASSACHUSETTS",
      city: "BOSTON",
      type: "Share Room",
      rooms: 3,
      img: "/images/home.jpg",
    },
    {
      name: "Rooms For Rent",
      date: "25-04-2022, 11:30 PM",
      price: 50000,
      state: "MASSACHUSETTS",
      city: "BOSTON",
      type: "Share Room",
      rooms: 3,
      img: "/images/home.jpg",
    },
    {
      name: "Rooms For Rent",
      date: "25-04-2022, 11:30 PM",
      price: 50000,
      state: "MASSACHUSETTS",
      city: "BOSTON",
      type: "Share Room",
      rooms: 3,
      img: "/images/home.jpg",
    },
    {
      name: "Rooms For Rent",
      date: "25-04-2022, 11:30 PM",
      price: 50000,
      state: "MASSACHUSETTS",
      city: "BOSTON",
      type: "Share Room",
      rooms: 3,
      img: "/images/home.jpg",
    },
    {
      name: "Rooms For Rent",
      date: "25-04-2022, 11:30 PM",
      price: 50000,
      state: "MASSACHUSETTS",
      city: "BOSTON",
      type: "Share Room",
      rooms: 3,
      img: "/images/home.jpg",
    },
    {
      name: "Rooms For Rent",
      date: "25-04-2022, 11:30 PM",
      price: 50000,
      state: "MASSACHUSETTS",
      city: "BOSTON",
      type: "Share Room",
      rooms: 3,
      img: "/images/home.jpg",
    },
    {
      name: "Rooms For Rent",
      date: "25-04-2022, 11:30 PM",
      price: 50000,
      state: "MASSACHUSETTS",
      city: "BOSTON",
      type: "Share Room",
      rooms: 3,
      img: "/images/home.jpg",
    },
    {
      name: "Rooms For Rent",
      date: "25-04-2022, 11:30 PM",
      price: 50000,
      state: "MASSACHUSETTS",
      city: "BOSTON",
      type: "Share Room",
      rooms: 3,
      img: "/images/home.jpg",
    },
    {
      name: "Rooms For Rent",
      date: "25-04-2022, 11:30 PM",
      price: 50000,
      state: "MASSACHUSETTS",
      city: "BOSTON",
      type: "Share Room",
      rooms: 3,
      img: "/images/home.jpg",
    },
    {
      name: "Rooms For Rent",
      date: "25-04-2022, 11:30 PM",
      price: 50000,
      state: "MASSACHUSETTS",
      city: "BOSTON",
      type: "Share Room",
      rooms: 3,
      img: "/images/home.jpg",
    },
    {
      name: "Rooms For Rent",
      date: "25-04-2022, 11:30 PM",
      price: 50000,
      state: "MASSACHUSETTS",
      city: "BOSTON",
      type: "Share Room",
      rooms: 3,
      img: "/images/home.jpg",
    },
    {
      name: "Rooms For Rent",
      date: "25-04-2022, 11:30 PM",
      price: 50000,
      state: "MASSACHUSETTS",
      city: "BOSTON",
      type: "Share Room",
      rooms: 3,
      img: "/images/home.jpg",
    },
    {
      name: "Rooms For Rent",
      date: "25-04-2022, 11:30 PM",
      price: 50000,
      state: "MASSACHUSETTS",
      city: "BOSTON",
      type: "Share Room",
      rooms: 3,
      img: "/images/home.jpg",
    },
    {
      name: "Rooms For Rent",
      date: "25-04-2022, 11:30 PM",
      price: 50000,
      state: "MASSACHUSETTS",
      city: "BOSTON",
      type: "Share Room",
      rooms: 3,
      img: "/images/home.jpg",
    },
    {
      name: "Rooms For Rent",
      date: "25-04-2022, 11:30 PM",
      price: 50000,
      state: "MASSACHUSETTS",
      city: "BOSTON",
      type: "Share Room",
      rooms: 3,
      img: "/images/home.jpg",
    },
  ],
}

export default RentRoomPage
