export const LOCALSTORE_REQUEST = "LOCALSTORE_REQUEST"
export const LOCALSTORE_SUCCESS = "LOCALSTORE_SUCCESS"
export const LOCALSTORE_FAILURE = "LOCALSTORE_FAILURE"

export const LOCALWORKERS_REQUEST = "LOCALWORKERS_REQUEST"
export const LOCALWORKERS_SUCCESS = "LOCALWORKERS_SUCCESS"
export const LOCALWORKERS_FAILURE = "LOCALWORKERS_FAILURE"
