export const RIDE_SCHOOL_REQUEST = "RIDE_SCHOOL_REQUEST"
export const RIDE_SCHOOL_SUCCESS = "RIDE_SCHOOL_SUCCESS"
export const RIDE_SCHOOL_FAILURE = "RIDE_SCHOOL_FAILURE"

export const RIDE_OLDAGE_REQUEST = "RIDE_OLDAGE_REQUEST"
export const RIDE_OLDAGE_SUCCESS = "RIDE_OLDAGE_SUCCESS"
export const RIDE_OLDAGE_FAILURE = "RIDE_OLDAGE_FAILURE"

export const RIDE_AIRPORT_REQUEST = "RIDE_AIRPORT_REQUEST"
export const RIDE_AIRPORT_SUCCESS = "RIDE_AIRPORT_SUCCESS"
export const RIDE_AIRPORT_FAILURE = "RIDE_AIRPORT_FAILURE"
